# Generated by Django 5.1.4 on 2025-01-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_rename_birth_date_trainer_bith_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='bith_date',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(null=True, upload_to='trainer_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('E', 'Eléctrico'), ('A', 'Agua'), ('T', 'Tierra'), ('L', 'Lagartija'), ('P', 'Planta')], max_length=30),
        ),
    ]
